export const ACTION_ADD_CARD = "ACTION_ADD_CARD";
export const ACTION_ADD_WISH = "ACTION_ADD_WISH";
export const ACTION_REMOVE_CARD = "ACTION_REMOVE_CARD";
export const ACTION_REMOVE_WISH = "ACTION_REMOVE_WISH";
