//ACTION TYPES
// da cancellare
export const FETCH_POSTS_LIST_REQUEST = "FETCH_POSTS_LIST_REQUEST";
export const FETCH_POSTS_LIST_SUCCESS = "FETCH_POSTS_LIST_SUCCESS";
export const FETCH_POSTS_LIST_FAILURE = "FETCH_POSTS_LIST_FAILURE";
export const FETCH_POSTS_LIST_SKIPPED = "FETCH_POSTS_LIST_SKIPPED";

export const FETCH_COMMENTS_LIST_REQUEST = "FETCH_COMMENTS_LIST_REQUEST";
export const FETCH_COMMENTS_LIST_SUCCESS = "FETCH_COMMENTS_LIST_SUCCESS";
export const FETCH_COMMENTS_LIST_FAILURE = "FETCH_COMMENTS_LIST_FAILURE";

export const ACTION_SELECT_POST = "ACTION_SELECT_POST";

export const ACTION_SET_LIKE_POST = "ACTION_SET_LIKE_POST";
export const ACTION_UNSET_LIKE_POST = "ACTION_UNSET_LIKE_POST";

export const ACTION_SET_LIKE_COMMENT = "ACTION_SET_LIKE_COMMENT";
export const ACTION_UNSET_LIKE_COMMENT = "ACTION_UNSET_LIKE_COMMENT";
// da cancellare

export const ACTION_ADD_CARD = "ACTION_ADD_CARD";
export const ACTION_ADD_WISH = "ACTION_ADD_WISH";
export const ACTION_REMOVE_CARD = "ACTION_REMOVE_CARD";
export const ACTION_REMOVE_WISH = "ACTION_REMOVE_WISH";
